import React, { useEffect, useState } from 'react';
import { Link, Navigate, useParams } from 'react-router-dom';
import { list, save, canAccess, importFolder, removeDocument } from '../lib/localStore';
import Modal from '../components/Modal';
import Preview from '../components/Preview';
export default function FolderDetail({ folders, user, users, run, refresh }) {
  const { id } = useParams(); const folder = folders.find(f => f.id === id && canAccess(user, f));
  const [documents, setDocuments] = useState([]), [loading, setLoading] = useState(true), [preview, setPreview] = useState(null), [pending, setPending] = useState(null), [notes, setNotes] = useState(folder?.notes || ''), [busy, setBusy] = useState(false);
  const load = async () => setDocuments((await list('documents')).filter(d => d.folderId === id));
  useEffect(() => { run(load).finally(() => setLoading(false)); }, [id]);
  if (!folder) return <><Link to="/">← Voltar</Link><h1>Pasta não encontrada ou acesso não permitido.</h1></>;
  const change = operation => { setBusy(true); run(operation).finally(() => setBusy(false)); };
  return <><Link to="/">← Voltar às pastas</Link><div className="banner"><span>PASTA MÉDICA</span><h1>{folder.title}</h1><p>{folder.patient} · {folder.reference || 'Sem referência'}</p></div><div className="detail"><section><h2>Laudos e exames <small>({documents.length})</small></h2>{loading ? <p>Carregando arquivos…</p> : documents.length ? documents.map(d => <article className="document card" key={d.id}><div><strong>{d.name}</strong><p className="muted">{d.path} · {(d.size / 1024).toFixed(1)} KB</p></div><select aria-label={'Status de ' + d.name} value={d.status} disabled={busy} onChange={e => change(async () => { await save('documents', { ...d, status: e.target.value }); await load(); })}><option value="novo">Novo</option><option value="em_analise">Em análise</option><option value="finalizado">Finalizado</option></select><button onClick={() => setPreview(d)}>Visualizar</button>{(user.role === 'admin' || folder.owner === user.id) && <button className="danger" disabled={busy} onClick={() => setPending(d)}>Excluir</button>}</article>) : <div className="empty">Esta pasta não possui arquivos.</div>}</section><aside><section className="card"><h2>Profissionais autorizados</h2><p>Responsável: {users.find(u => u.id === folder.owner)?.name}</p>{folder.members.map(id => <p key={id}>{users.find(u => u.id === id)?.name}</p>)}</section><form className="card" onSubmit={e => { e.preventDefault(); change(async () => { await save('folders', { ...folder, notes }); await refresh(); }); }}><label>Observações<textarea value={notes} onChange={e => setNotes(e.target.value)} rows={6} /></label><button disabled={busy}>Salvar observações</button></form></aside></div>{preview && <Preview document={preview} close={() => setPreview(null)} />}{pending && <Modal title="Excluir documento?" close={() => !busy && setPending(null)}><p>O arquivo {pending.name} será removido deste protótipo.</p><div className="actions"><button disabled={busy} onClick={() => setPending(null)}>Cancelar</button><button className="danger" disabled={busy} onClick={() => change(async () => { await removeDocument(pending, folder); await load(); await refresh(); setPending(null); })}>Confirmar exclusão</button></div></Modal>}</>;
}
